---
- name: ECS list S3 bucket
  hosts: ECS_TESTDRIVE
  gather_facts: False
  vars:
    #username: "<ENTER YOUR USERNAME>"
    username: "131887216500386603@ecstestdrive.emc.com"
    #password: "<ENTER YOUR PASSWORD>"
    password: "l9fBa0oZ2NzQAJPDFT00RQsRp4wAhnCxtu+fnsTE"
    #password: "DY5eoCSY4IIxrHyvnOuAFfnDVDE="
    #ECS_host: "<ENTER ECS IP/HOSTNAME>"
    ECS_host: "object.ecstestdrive.com"
    AWSsignatureV2date: "date +'%a, %d %b %Y %H:%M:%S %z'"
    AWSsignatureV4date: "date +'%Y%m%d'T'%H%M%S'Z"
    dateValue: "{{ AWSsignatureV4date }}"
    #NameSpace: ns1

  tasks:
  - name: Get date for s3 
    command: "{{ dateValue }}"
    register: result_date

  - name: Connect to ECS list S3 buckets
    uri:
      url: https://{{ECS_host}}/
      method: POST
      url_username: "{{username}}"
      url_password: "{{password}}"
      validate_certs: no
      follow_redirects: all
      headers:
        Content-Type: application/json
        Accept: application/json
        Authorization: AWS {{ username }}:{{ password }}
        #x-amz-date: "{{ result_date.stdout }}"
        Date: "{{ result_date.stdout }}"
        Host:  object.ecstestdrive.com
        #x-emc-dataservice-vpool:urn:storageos:ReplicationGroupInfo:104b3728-fba1-41b3-8055-4592348f1d24:global
        #x-emc-metadata-search:x-amz-meta-showname;String,x-amz-meta-showtype;String,x-amz-meta-episode;String,x-amz-meta-session;String,x-amz-meta-language;String,x-amz-meta-genre;String
        #X-SDS-AUTH-TOKEN: "{{ results_login.x_sds_auth_token }}"
      #body_format: json
      #body:
      #  {
      #    "name": "{{ BucketName }}",
      #    "owner": "{{ bucketOwner }}",
      #    "filesystem_enabled": "false",
      #    "head_type": "s3",
      #    "retention": "3",
      #  }
      return_content: yes
    register: results_ListBucket

  - debug:
     msg="{{ results_ListBucket }}"
