apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansiblealpine01-isi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Mi
  storageClassName: isilon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansiblealpine01-dep
  labels:
    app: ansiblealpine01-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ansiblealpine01-pod
      app: ansiblealpine01-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: ansiblealpine01-pod
      labels:
        name: ansiblealpine01-pod
        app: ansiblealpine01-app
    spec:
      hostAliases:
      - ip: "192.168.11.121"
        hostnames:
          - "isilon82dc1"
      - ip: "192.168.11.131"
        hostnames:
          - "isilon82dc2"
      - ip: "192.168.11.80"
        hostnames:
          - "ad2016"
      - ip: "192.168.11.99"
        hostnames:
          - "awxold"
      - ip: "192.168.11.101"
        hostnames:
          - "awxdemo"
      
      containers:
        - name: ansiblealpine01
          image: koutsane/koutsane:ansiblealpine
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: "/mnt/isilon"
              name: ansiblealpine01-vol01
      volumes:
        - name: ansiblealpine01-vol01
          persistentVolumeClaim:
            claimName: ansiblealpine01-isi-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ansiblealpine01-service
spec:
  type: NodePort
  ports:
    - targetPort: 22
      port: 22
      nodePort: 30001
  selector:
    name: ansiblealpine01-pod
    app: ansiblealpine01-app
