apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansibleubuntu01-rest-pvc
  namespace: default
spec:
  storageClassName: isilon
  dataSource:
    name: ansibleubuntu01-snap1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
