---
- name: Create Isilon Snapshot
  gather_facts: true
  hosts: isilon
  vars:
    isilonURL: "https://{{ansible_host}}:8080"
    snapName: API snapshot from ansible
    snapPath: /ifs/data
    snapExpire: "{{ ansible_date_time.epoch | int + ( 86400 * 3 ) }}" 
    userName: ansible
    userPass: ansible
  
  tasks:
    - name: get isilon API session IDs
      uri:
        url: {{ isilonURL }}/session/1/session
        method: POST
        validate_certs: no
        body_format: json
        body:
          {
            username: "{{ userName }}",
            password: "{{ userPass }}",
            services: ["platform", "namespace"]
          }
        status_code: 201

    - name: Create snapshot on isilon
      uri:
