- name: Isilon - test API access via get session token
  hosts: isilon
  vars:
    Isilon_IP: "https://{{ ansible_host }}:8080"
    isilonuser: "ansible"
    isilonpass: "ansible"

  tasks:
    - name: get isilon API session IDs
      uri:
        url: "{{ Isilon_IP }}/session/1/session"
        method: POST
        validate_certs: no
        body_format: json
        body:
          {
            username: "{{ isilonuser }}",
            password: "{{ isilonpass }}",
            services: ["platform", "namespace"]
	  }
        status_code: 201
      register: results_login
    
    - debug:
        msg="{{ results_login }}"
   
    - name: Delete isilon API session IDs
      uri:
        url: "{{ Isilon_IP }}/session/1/session"
        method: DELETE
        validate_certs: no
        headers:
          Cookie: "isisessid={{ results_login.cookies.isisessid }}"
          X-CSRF-Token: "{{ results_login.cookies.isicsrf }}"
          referer: "{{ Isilon_IP }}"
        status_code: 204
      register: results_DEL_cookie
    
    - debug:
        msg="{{ results_DEL_cookie }}"
