- name: Isilon New SMB share with ansible URI module
  hosts: isilon
  vars:
    Isilon_IP: "https://{{ ansible_host }}:8080"
    isilonuser: "ansible"
    isilonpass: "ansible"
    sharename: "API SMB Ansible Share"
    sharepath: /ifs/data/Ansible
    sharedescr: "Share Created by Ansible Core Isilon API playbook"
    domaingrp: "KRYPTOLULA\\domain users"

  tasks:
    - name: get isilon API session IDs
      uri:
        url: "{{ Isilon_IP }}/session/1/session"
        method: POST
        validate_certs: no
        body_format: json
        body:
          {
            username: "{{ isilonuser }}",
            password: "{{ isilonpass }}",
            services: ["platform", "namespace"]
	  }
        status_code: 201
   
 
    - name: make SMB share
      uri:
