---
- name: ECS list VDC nodes
  hosts: localhost
  gather_facts: False
  vars:
    username: "<ENTER YOUR USERNAME>"
    password: "<ENTER YOUR PASSWORD>"
    ECS_host: "<ENTER ECS IP/HOSTNAME>"

  tasks:

  - name: test ECS API basic authentication
    uri:
      validate_certs: no
      user: "{{ username }}"
      password: "{{ password }}"
      url: https://{{ECS_host}}/login
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
      return_content: yes
    register: results_login
    #no_log: True

  - debug:
     msg="{{ results_vdcNodes.json }}"


  - name: Connect to webservice using a previously stored cookie to list VDC nodes
